// svc/coruscant/src/lib/components/app-shell/AppSidebar.svelte
<script lang="ts">
import Icon from "@iconify/svelte";
import { Separator as SeparatorComp } from "@lerpz/ui/components/separator";
import {
    Sidebar,
    SidebarContent,
    SidebarFooter,
    SidebarHeader,
    SidebarRail,
} from "@lerpz/ui/components/sidebar";
import ModeSwitcher from "./ModeSwitcher.svelte";
import NavSecondary from "./NavSecondary.svelte";
import SidebarChats from "./SidebarChats.svelte";
import UserInfo from "./UserInfo.svelte";

const modes = [
    {
        variant: "chat" as const,
        name: "Chat",
        icon: "mdi:chat-bubble",
        plan: "Free",
        href: "/ai/chats",
    },
    {
        variant: "image" as const,
        name: "Image",
        icon: "mdi:image",
        plan: "Free",
        href: "/ai/images",
    },
    {
        variant: "video" as const,
        name: "Video",
        icon: "mdi:videocam",
        plan: "Enterprise",
        href: "/ai/videos",
    },
];
</script>

<Sidebar collapsible="icon">
  <SidebarHeader>
    <ModeSwitcher defaultMode={modes[0]!} {modes} />
  </SidebarHeader>
  <SeparatorComp />
  <SidebarContent>
    <SidebarChats />
    <NavSecondary class="mt-auto" />
  </SidebarContent>
  <SeparatorComp />
  <SidebarFooter>
    <UserInfo />
  </SidebarFooter>
  <SidebarRail />
</Sidebar>

// svc/portal/src/components/sidebar/app-sidebar.tsx
"use client";

import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarRail,
} from "@lerpz/ui/components/sidebar";
import { Image, MessageCircle, Video } from "lucide-react";
import type { ComponentProps } from "react";
// import { NavMain } from "@/components/sidebar/nav-main";
// import { NavProjects } from "@/components/sidebar/nav-projects";
import ModeSwitcher from "./mode-switcher";
import NavSecondary from "./nav-secondary";
import SidebarUserInfo from "./user-info";

const data = {
  user: {
    name: "shadcn",
    email: "m@example.com",
    avatar: "/avatars/shadcn.jpg",
  },
  modes: [
    {
      name: "Chat",
      logo: MessageCircle,
      plan: "Free",
    },
    {
      name: "Image",
      logo: Image,
      plan: "Free",
    },
    {
      name: "Video",
      logo: Video,
      plan: "Enterprise",
    },
  ],
};

export default function AppSidebar({
  ...props
}: ComponentProps<typeof Sidebar>) {
  return (
    <Sidebar collapsible="icon" {...props}>
      <SidebarHeader>
        <ModeSwitcher modes={data.modes} />
      </SidebarHeader>
      <SidebarContent>
        {/*<NavMain items={data.navMain} />*/}
        {/*<NavProjects projects={data.projects} />*/}
        <NavSecondary className="mt-auto" />
      </SidebarContent>
      <SidebarFooter>
        <SidebarUserInfo />
      </SidebarFooter>
      <SidebarRail />
    </Sidebar>
  );
}
