// svc/coruscant/src/lib/components/app-shell/NavSecondary.svelte
<script lang="ts">
import Icon from "@iconify/svelte";
import {
    SidebarGroup,
    SidebarGroupContent,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from "@lerpz/ui/components/sidebar";
import { page } from "$app/state";

let { class: className = "" }: { class?: string } = $props();

const pathname = $derived(page.url.pathname);

const pages = [
    { title: "Docs", url: "/docs", icon: "mdi:file-document-outline" },
    { title: "Settings", url: "/settings", icon: "mdi:cog-outline" },
    { title: "Roadmap", url: "/roadmap", icon: "mdi:road-variant" },
];
</script>

<SidebarGroup class={className}>
  <SidebarGroupContent>
    <SidebarMenu>
      {#each pages as item}
        <SidebarMenuItem>
          <SidebarMenuButton href={item.url} isActive={item.url === pathname}>
            <Icon icon={item.icon} />
            <span>{item.title}</span>
          </SidebarMenuButton>
        </SidebarMenuItem>
      {/each}
    </SidebarMenu>
  </SidebarGroupContent>
</SidebarGroup>

// svc/portal/src/components/sidebar/nav-secondary.tsx
import {
  SidebarGroup,
  SidebarGroupContent,
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
} from "@lerpz/ui/components/sidebar";
import { Construction, Settings2 } from "lucide-react";
import Link from "next/link";
import type { ComponentPropsWithoutRef } from "react";

type NavSecondaryProps = ComponentPropsWithoutRef<typeof SidebarGroup>;

const pages = [
  {
    title: "Settings",
    url: "/settings",
    icon: Settings2,
  },
  {
    title: "Roadmap",
    url: "/roadmap",
    icon: Construction,
  },
];

export default function NavSecondary({ ...props }: NavSecondaryProps) {
  return (
    <SidebarGroup {...props}>
      <SidebarGroupContent>
        <SidebarMenu>
          {pages.map((item) => (
            <SidebarMenuItem key={item.title}>
              <SidebarMenuButton
                render={
                  <Link href={item.url}>
                    <item.icon />
                    <span>{item.title}</span>
                  </Link>
                }
              ></SidebarMenuButton>
            </SidebarMenuItem>
          ))}
        </SidebarMenu>
      </SidebarGroupContent>
    </SidebarGroup>
  );
}
