// svc/coruscant/src/lib/components/landing-page/Header.svelte
<script lang="ts">
import { Button } from "@lerpz/ui/components/button";
import { msalStore } from "$lib/auth/msal.svelte.js";
import ThemeButton from "$lib/components/ThemeButton.svelte";

const navLinks = [
    { label: "Tools", href: "/ai" },
    { label: "Roadmap", href: "/roadmap" },
    { label: "Docs", href: "/docs" },
    { label: "Changelog", href: "/changelog" },
    { label: "Status", href: "/status" },
];

const isAuthenticated = $derived(msalStore.isAuthenticated);
</script>

<header class="sticky top-0 z-50 border-b border-border/60 bg-background/80 backdrop-blur-md">
  <div class="mx-auto flex max-w-[1024px] items-center justify-between px-4 py-3">
    <a href="/" class="flex items-center gap-2.5 font-bold text-foreground transition-opacity hover:opacity-80">
      <img src="/lerpz.svg" alt="Lerpz Logo" class="h-7 w-7" />
      <span class="text-lg tracking-tight">Lerpz AI</span>
    </a>

    <nav class="hidden items-center gap-6 md:flex">
      {#each navLinks as link}
        <a href={link.href} class="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground">
          {link.label}
        </a>
      {/each}
    </nav>

    <div class="flex items-center gap-2">
      {#if isAuthenticated}
        <a href="/ai/chats" class="hidden text-sm font-medium text-muted-foreground transition-colors hover:text-foreground sm:block">
          Dashboard
        </a>
      {/if}
      <ThemeButton />
      <Button onclick={() => (isAuthenticated ? msalStore.switchAccount() : msalStore.loginRedirect())}>
        {isAuthenticated ? "Switch account" : "Sign in"}
      </Button>
    </div>
  </div>
</header>

// svc/portal/src/components/landing-page/header.tsx
"use client";

import { useIsAuthenticated } from "@azure/msal-react";
import Image from "next/image";
import Link from "next/link";
import LoginButton from "../login-button";

const navLinks = [
    { label: "Tools", href: "/ai" },
    { label: "Roadmap", href: "/roadmap" },
    { label: "Docs", href: "/docs" },
    { label: "Changelog", href: "/changelog" },
    { label: "Status", href: "/status" },
];

export default function Header() {
    const isAuthenticated = useIsAuthenticated();

    return (
        <header className="sticky top-0 z-50 border-b border-border/60 bg-background/80 backdrop-blur-md">
            <div className="mx-auto flex max-w-[1024px] items-center justify-between px-4 py-3">
                {/* Logo */}
                <Link
                    href="/"
                    className="flex items-center gap-2.5 font-bold text-foreground transition-opacity hover:opacity-80"
                >
                    <Image
                        src="/lerpz.svg"
                        alt="Lerpz Logo"
                        width={28}
                        height={28}
                    />
                    <span className="text-lg tracking-tight">Lerpz AI</span>
                </Link>

                {/* Nav */}
                <nav className="hidden items-center gap-6 md:flex">
                    {navLinks.map((link) => (
                        <Link
                            key={link.href}
                            href={link.href}
                            className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground"
                        >
                            {link.label}
                        </Link>
                    ))}
                </nav>

                {/* Actions */}
                <div className="flex items-center gap-3">
                    {isAuthenticated && (
                        <Link
                            href="/ai/chats"
                            className="hidden text-sm font-medium text-muted-foreground transition-colors hover:text-foreground sm:block"
                        >
                            Dashboard
                        </Link>
                    )}
                    <LoginButton>
                        {isAuthenticated ? "Switch account" : "Sign in"}
                    </LoginButton>
                </div>
            </div>
        </header>
    );
}
