// svc/portal/src/app/(dashboard)/ai/images/page.tsx
"use client";

import Image from "next/image";
import { useAi } from "../layout";

export default function Images() {
    const { generatedImage, isImageLoading, imageError } = useAi();

    return (
        <div className="max-w-[1024px] w-full h-full mx-auto">
            {imageError && (
                <p className="text-sm text-destructive mb-4">{imageError}</p>
            )}
            {generatedImage ? (
                <Image
                    src={generatedImage}
                    alt="Generated image"
                    width={1200}
                    height={800}
                    unoptimized
                />
            ) : (
                <p>
                    {isImageLoading
                        ? "Generating image..."
                        : "Describe an image in the chatbox below to generate one!"}
                </p>
            )}
        </div>
    );
}

// svc/coruscant/src/routes/(dashboard)/ai/images/+page.svelte
<script lang="ts">
import { getAiContext } from "$lib/ai/context.svelte.js";

const ai = getAiContext();
</script>

<div class="max-w-5xl w-full h-full mx-auto">
  {#if ai.imageError}
    <p class="text-sm text-destructive mb-4">{ai.imageError}</p>
  {/if}
  {#if ai.generatedImage}
    <img src={ai.generatedImage} alt="Generated" class="max-w-full" />
  {:else}
    <p>{ai.isImageLoading ? "Generating image..." : "Describe an image in the chatbox below to generate one!"}</p>
  {/if}
</div>
