// packages/ui/src/components/text-loop.tsx
"use client";
import { cn } from "@lerpz/ui/lib/utils";
import {
  AnimatePresence,
  type AnimatePresenceProps,
  motion,
  type Transition,
  type Variants,
} from "motion/react";
import { Children, useEffect, useState } from "react";

export type TextLoopProps = {
  children: React.ReactNode[];
  className?: string;
  interval?: number;
  transition?: Transition;
  variants?: Variants;
  onIndexChange?: (index: number) => void;
  trigger?: boolean;
  mode?: AnimatePresenceProps["mode"];
};

export function TextLoop({
  children,
  className,
  interval = 2,
  transition = { duration: 0.3 },
  variants,
  onIndexChange,
  trigger = true,
  mode = "popLayout",
}: TextLoopProps) {
  const [currentIndex, setCurrentIndex] = useState(0);
  const items = Children.toArray(children);

  useEffect(() => {
    if (!trigger) return;

    const intervalMs = interval * 1000;
    const timer = setInterval(() => {
      setCurrentIndex((current) => {
        const next = (current + 1) % items.length;
        onIndexChange?.(next);
        return next;
      });
    }, intervalMs);
    return () => clearInterval(timer);
  }, [items.length, interval, onIndexChange, trigger]);

  const motionVariants: Variants = {
    initial: { y: 20, opacity: 0 },
    animate: { y: 0, opacity: 1 },
    exit: { y: -20, opacity: 0 },
  };

  return (
    <div className={cn("relative inline-block whitespace-nowrap", className)}>
      <AnimatePresence mode={mode} initial={false}>
        <motion.div
          key={currentIndex}
          initial="initial"
          animate="animate"
          exit="exit"
          transition={transition}
          variants={variants || motionVariants}
        >
          {items[currentIndex]}
        </motion.div>
      </AnimatePresence>
    </div>
  );
}

// packages/ui/src/components/text-loop/TextLoop.svelte
<script lang="ts">
import { fly } from "svelte/transition";
import { cn } from "../../lib/utils.js";

let {
    items,
    class: className = "",
    interval = 2,
}: {
    items: string[];
    class?: string;
    interval?: number;
} = $props();

let currentIndex = $state(0);

$effect(() => {
    const ms = interval * 1000;
    const timer = setInterval(() => {
        currentIndex = (currentIndex + 1) % items.length;
    }, ms);
    return () => clearInterval(timer);
});
</script>

<div class={cn("relative inline-grid whitespace-nowrap", className)}>
  {#key currentIndex}
    <span
      class="col-start-1 row-start-1"
      in:fly={{ y: 20, duration: 300 }}
      out:fly={{ y: -20, duration: 300 }}
      style="display: inline-block;"
    >
      {items[currentIndex]}
    </span>
  {/key}
</div>
