// svc/portal/src/app/(dashboard)/ai/chats/[id]/page.tsx
"use client";

import { Skeleton } from "@lerpz/ui/components/skeleton";
import { use, useEffect } from "react";

import { useGetChat } from "@/services/api/chats/chats";
import { useAi } from "../../layout";
import ChatView from "../chat-view";

interface ChatPageProps {
  params: Promise<{ id: string }>;
}

export default function ChatPage({ params }: ChatPageProps) {
  const { id } = use(params);
  const {
    chatMessages,
    isChatStreaming,
    chatError,
    conversationId,
    enterConversation,
  } = useAi();

  // "Live" means the hook is actively holding data for this specific
  // conversation — either because we just created it (and were redirected
  // here) or because the user already sent a message during this session.
  const isLive = conversationId === id && chatMessages.length > 0;

  const { data: response, isLoading } = useGetChat(id, {
    query: {
      // Skip fetching while the SSE stream already has the full history.
      enabled: !isLive,
    },
  });

  // Once the API returns data and we are not yet in "live" mode for this
  // conversation, seed the hook so that the next send() continues it.
  useEffect(() => {
    if (isLive || conversationId === id) return;
    if (response?.status !== 200 || !response.data) return;

    enterConversation(id, response.data.messages);
  }, [id, isLive, conversationId, response, enterConversation]);

  if (!isLive && isLoading) {
    return <ChatLoadingSkeleton />;
  }

  if (!isLive && response?.status !== 200) {
    return (
      <p className="text-muted-foreground px-2 py-4 text-center text-xs">
        Error: {response?.status}
      </p>
    );
  }

  const messages = isLive
    ? chatMessages
    : response?.status === 200 && response.data
      ? response.data.messages
      : [];

  return (
    <ChatView
      messages={messages}
      isStreaming={isLive && isChatStreaming}
      error={isLive ? chatError : null}
    />
  );
}

function ChatLoadingSkeleton() {
  return (
    <div className="mx-auto max-w-[750px] flex flex-col gap-4 pt-4 pb-8 px-4">
      <div className="flex justify-end gap-3">
        <Skeleton className="h-10 w-56 rounded-2xl rounded-br-md" />
        <Skeleton className="size-7 rounded-full shrink-0 mt-1" />
      </div>
      <div className="flex justify-start gap-3">
        <Skeleton className="size-7 rounded-full shrink-0 mt-1" />
        <Skeleton className="h-24 w-80 rounded-2xl rounded-bl-md" />
      </div>
      <div className="flex justify-end gap-3">
        <Skeleton className="h-10 w-40 rounded-2xl rounded-br-md" />
        <Skeleton className="size-7 rounded-full shrink-0 mt-1" />
      </div>
      <div className="flex justify-start gap-3">
        <Skeleton className="size-7 rounded-full shrink-0 mt-1" />
        <Skeleton className="h-32 w-96 rounded-2xl rounded-bl-md" />
      </div>
    </div>
  );
}

// svc/coruscant/src/routes/(dashboard)/ai/chats/[id]/+page.svelte
<script lang="ts">
import { Skeleton } from "@lerpz/ui/components/skeleton";
import { createQuery } from "@tanstack/svelte-query";
import { getAiContext } from "$lib/ai/context.svelte.js";
import { getChat } from "$lib/api/chats/chats.js";
import ChatView from "$lib/components/chatbox/ChatView.svelte";
import type { PageProps } from "./$types.js";

let { params }: PageProps = $props();

const id = $derived(params.id);
const ai = getAiContext();

const isLive = $derived(ai.conversationId === id && ai.chatMessages.length > 0);

const query = createQuery(() => ({
    queryKey: [`/api/v1/chats/${id}`],
    queryFn: ({ signal }: { signal: AbortSignal }) => getChat(id, { signal }),
    enabled: !isLive,
}));

$effect(() => {
    if (isLive || ai.conversationId === id) return;
    const resp = query.data;
    if (resp?.status !== 200 || !resp.data) return;
    ai.enterConversation(id, resp.data.messages);
});

const messages = $derived(
    isLive
        ? ai.chatMessages
        : query.data?.status === 200 && query.data.data
          ? query.data.data.messages
          : [],
);
</script>

{#if !isLive && query.isLoading}
  <div class="mx-auto max-w-200 flex flex-col gap-4 pt-4 pb-8 px-4">
    <div class="flex justify-end gap-3">
      <Skeleton class="h-10 w-56 rounded-2xl rounded-br-md" />
      <Skeleton class="size-7 rounded-full shrink-0 mt-1" />
    </div>
    <div class="flex justify-start gap-3">
      <Skeleton class="size-7 rounded-full shrink-0 mt-1" />
      <Skeleton class="h-24 w-80 rounded-2xl rounded-bl-md" />
    </div>
  </div>
{:else if !isLive && query.data?.status !== 200}
  <p class="text-muted-foreground px-2 py-4 text-center text-xs">
    Error: {query.data?.status}
  </p>
{:else}
  <ChatView {messages} isStreaming={isLive && ai.isChatStreaming} error={isLive ? ai.chatError : null} onRetry={ai.retryChat} />
{/if}
