// svc/coruscant/src/lib/components/app-shell/AppTopbar.svelte
<script lang="ts">
import { SidebarTrigger } from "@lerpz/ui/components/sidebar";
import ThemeButton from "$lib/components/ThemeButton.svelte";
</script>

<header class="flex items-center shrink-0 gap-2 border-b px-4 h-12">
  <div class="grow">
    <SidebarTrigger class="ml-1" />
  </div>
  <div>
    <ThemeButton />
  </div>
</header>

// svc/portal/src/components/app-shell/app-topbar.tsx
import { SidebarTrigger } from "@lerpz/ui/components/sidebar";
import { ThemeButton } from "../theme-button";

export default function AppTopbar() {
  return (
    <header className="flex items-center shrink-0 gap-2 border-b px-4 h-12">
      <div className="grow">
        <SidebarTrigger className="ml-1" />
      </div>
      <div>
        <ThemeButton />
      </div>
    </header>
  );
}
