// svc/app/src/lib/components/app-shell/AppShell.svelte
<script lang="ts">
import { SidebarInset, SidebarProvider } from "@lerpz/ui/components/sidebar";
import type { Snippet } from "svelte";
import AppSidebar from "./AppSidebar.svelte";
import AppTopbar from "./AppTopbar.svelte";

let { children }: { children: Snippet } = $props();
</script>

<SidebarProvider>
  <AppSidebar />
  <SidebarInset>
    <AppTopbar />
    {@render children()}
  </SidebarInset>
</SidebarProvider>

// svc/portal/src/components/app-shell/index.tsx
import { SidebarInset, SidebarProvider } from "@lerpz/ui/components/sidebar";
import AppSidebar from "./app-sidebar";
import AppTopbar from "./app-topbar";

export function AppShell({ children }: { children: React.ReactNode }) {
  return (
    <SidebarProvider>
      <AppSidebar />
      <SidebarInset>
        <AppTopbar />
        {children}
      </SidebarInset>
    </SidebarProvider>
  );
}

export { AppSidebar };
