// svc/coruscant/src/lib/components/app-shell/NavSecondary.svelte
<script lang="ts">
import Icon from "@iconify/svelte";
import {
    SidebarGroup,
    SidebarGroupContent,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from "@lerpz/ui/components/sidebar";
import { page } from "$app/state";

let { class: className = "" }: { class?: string } = $props();

const pathname = $derived(page.url.pathname);

const pages = [
    { title: "Docs", url: "/docs", icon: "mdi:file-document-outline" },
    { title: "Settings", url: "/settings", icon: "mdi:cog-outline" },
    { title: "Roadmap", url: "/roadmap", icon: "mdi:road-variant" },
];
</script>

<SidebarGroup class={className}>
  <SidebarGroupContent>
    <SidebarMenu>
      {#each pages as item}
        <SidebarMenuItem>
          <SidebarMenuButton href={item.url} isActive={item.url === pathname}>
            <Icon icon={item.icon} />
            <span>{item.title}</span>
          </SidebarMenuButton>
        </SidebarMenuItem>
      {/each}
    </SidebarMenu>
  </SidebarGroupContent>
</SidebarGroup>

// svc/portal/src/components/app-shell/nav-secondary.tsx
import {
    SidebarGroup,
    SidebarGroupContent,
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
} from "@lerpz/ui/components/sidebar";
import Link from "next/link";
import { usePathname } from "next/navigation";
import type { ComponentPropsWithoutRef } from "react";
import { MdConstruction, MdDescription, MdSettings } from "react-icons/md";

type NavSecondaryProps = ComponentPropsWithoutRef<typeof SidebarGroup>;

const pages = [
    {
        title: "Docs",
        url: "/docs",
        icon: MdDescription,
    },
    {
        title: "Settings",
        url: "/settings",
        icon: MdSettings,
    },
    {
        title: "Roadmap",
        url: "/roadmap",
        icon: MdConstruction,
    },
];

export default function NavSecondary({ ...props }: NavSecondaryProps) {
    const pathname = usePathname();

    return (
        <SidebarGroup {...props}>
            <SidebarGroupContent>
                <SidebarMenu>
                    {pages.map((item) => (
                        <SidebarMenuItem key={item.title}>
                            <SidebarMenuButton
                                isActive={item.url === pathname}
                                render={
                                    <Link href={item.url}>
                                        <item.icon />
                                        <span>{item.title}</span>
                                    </Link>
                                }
                            ></SidebarMenuButton>
                        </SidebarMenuItem>
                    ))}
                </SidebarMenu>
            </SidebarGroupContent>
        </SidebarGroup>
    );
}
