// svc/app/src/lib/components/app-shell/UserInfo.svelte
<script lang="ts">
import Icon from "@iconify/svelte";
import {
    Avatar,
    AvatarFallback,
    AvatarImage,
} from "@lerpz/ui/components/avatar";
import {
    DropdownMenu,
    DropdownMenuContent,
    DropdownMenuGroup,
    DropdownMenuItem,
    DropdownMenuLabel,
    DropdownMenuSeparator,
    DropdownMenuTrigger,
} from "@lerpz/ui/components/dropdown-menu";
import {
    SidebarMenu,
    SidebarMenuButton,
    SidebarMenuItem,
    useSidebar,
} from "@lerpz/ui/components/sidebar";
import { msalStore } from "$lib/auth/msal.svelte.js";
import { getCurrentUserPhotoUrl } from "$lib/graph/photo.js";

const sidebar = useSidebar();
const account = $derived(msalStore.activeAccount);

let avatarSrc = $state<string | undefined>(undefined);

$effect(() => {
    const accountId = account?.homeAccountId;
    if (!accountId) {
        avatarSrc = undefined;
        return;
    }
    getCurrentUserPhotoUrl().then((url) => {
        avatarSrc = url ?? undefined;
    });
});

const avatarFallback = $derived(
    account?.name
        ?.split(" ")
        .map((n) => n?.[0]?.toUpperCase() ?? "")
        .filter(Boolean)
        .slice(0, 2)
        .join("") || "?",
);
</script>

<SidebarMenu class="w-full">
  <SidebarMenuItem>
    <DropdownMenu
      side={sidebar.isMobile ? "bottom" : "right"}
      align="end"
      sideOffset={4}
    >
      <DropdownMenuTrigger class="w-full">
        <SidebarMenuButton size="lg" class="group-data-[state=collapsed]:size-8 group-data-[state=collapsed]:p-0">
          <Avatar class="h-8 w-8 shrink-0">
            <AvatarImage src={avatarSrc ?? ""} alt={account?.name ?? ""} />
            <AvatarFallback>{avatarFallback}</AvatarFallback>
          </Avatar>
          <div class="grid flex-1 text-left text-sm leading-tight group-data-[state=collapsed]:hidden">
            <span class="truncate font-medium">{account?.name}</span>
            <span class="truncate text-xs text-muted-foreground">{account?.username}</span>
          </div>
          <Icon icon="fa6-solid:ellipsis-vertical" class="ml-auto size-4 group-data-[state=collapsed]:hidden" />
        </SidebarMenuButton>
      </DropdownMenuTrigger>
      <DropdownMenuContent>
        <DropdownMenuGroup>
          <DropdownMenuLabel class="p-0 font-normal">
            <div class="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
              <Avatar class="h-8 w-8">
                <AvatarImage src={avatarSrc ?? ""} alt={account?.name ?? ""} />
                <AvatarFallback class="rounded-lg">{avatarFallback}</AvatarFallback>
              </Avatar>
              <div class="grid flex-1 text-left text-sm leading-tight">
                <span class="truncate font-medium">{account?.name}</span>
                <span class="truncate text-xs text-muted-foreground">{account?.username}</span>
              </div>
            </div>
          </DropdownMenuLabel>
        </DropdownMenuGroup>
        <DropdownMenuSeparator />
        <DropdownMenuGroup>
          <DropdownMenuItem value="upgrade">
            <Icon icon="fa6-solid:wand-magic-sparkles" />
            Upgrade to Pro
          </DropdownMenuItem>
        </DropdownMenuGroup>
        <DropdownMenuSeparator />
        <DropdownMenuGroup>
          <DropdownMenuItem value="account"><Icon icon="fa6-solid:user-check" />Account</DropdownMenuItem>
          <DropdownMenuItem value="notifications"><Icon icon="fa6-regular:bell" />Notifications</DropdownMenuItem>
        </DropdownMenuGroup>
        <DropdownMenuSeparator />
        <DropdownMenuItem value="switch" onclick={() => msalStore.switchAccount()}>
          <Icon icon="fa6-solid:arrow-right-arrow-left" />
          Switch Account
        </DropdownMenuItem>
        <DropdownMenuItem value="logout" onclick={() => msalStore.logoutRedirect()}>
          <Icon icon="fa6-solid:right-from-bracket" />
          Log out
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  </SidebarMenuItem>
</SidebarMenu>

// svc/portal/src/components/app-shell/user-info.tsx
"use client";

import { InteractionStatus } from "@azure/msal-browser";
import { useMsal } from "@azure/msal-react";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "@lerpz/ui/components/avatar";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuGroup,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@lerpz/ui/components/dropdown-menu";
import {
  SidebarMenu,
  SidebarMenuButton,
  SidebarMenuItem,
  useSidebar,
} from "@lerpz/ui/components/sidebar";
import {
  BadgeCheck,
  Bell,
  ChevronsUpDown,
  LogOut,
  Sparkles,
  Users,
} from "lucide-react";
import { useEffect, useState } from "react";
import { loginRequest } from "@/lib/msal-config";
import { getCurrentUserPhotoUrl } from "@/services/graph/photo";

export default function SidebarUserInfo() {
  const [avatarSrc, setAvatarSrc] = useState<string>();

  const { instance, inProgress } = useMsal();
  const account = instance.getActiveAccount();
  const accountId = account?.homeAccountId;

  const { isMobile } = useSidebar();

  useEffect(() => {
    let isMounted = true;

    (async () => {
      if (!accountId) {
        setAvatarSrc(undefined);
        return;
      }

      if (inProgress !== InteractionStatus.None) {
        return;
      }

      const url = await getCurrentUserPhotoUrl();
      if (!isMounted) return;

      setAvatarSrc(url ?? undefined);
    })();

    return () => {
      isMounted = false;
    };
  }, [accountId, inProgress]);

  const avatarFallback =
    account?.name
      ?.split(" ")
      .map((n) => (n ? n[0]?.toUpperCase() : ""))
      .filter((n) => n)
      .slice(0, 2)
      .join("") || "?";

  const handleAccountSwitch = async () => {
    try {
      await instance.loginRedirect({
        prompt: "select_account",
        ...loginRequest,
      });
    } catch (error) {
      console.error("Account switch failed:", error);
    }
  };

  const handleLogout = async () => {
    try {
      await instance.logoutRedirect();
    } catch (error) {
      console.error("Logout failed:", error);
    }
  };
  return (
    <SidebarMenu>
      <SidebarMenuItem>
        <DropdownMenu>
          <DropdownMenuTrigger
            render={
              <SidebarMenuButton
                size="lg"
                className="data-[state=open]:bg-sidebar-accent data-[state=open]:text-sidebar-accent-foreground"
              >
                <Avatar className="h-8 w-8 rounded-lg">
                  <AvatarImage src={avatarSrc} />
                  <AvatarFallback className="rounded-lg">
                    {avatarFallback}
                  </AvatarFallback>
                </Avatar>
                <div className="grid flex-1 text-left text-sm leading-tight">
                  <span className="truncate font-medium">{account?.name}</span>
                  <span className="truncate text-xs">{account?.username}</span>
                </div>
                <ChevronsUpDown className="ml-auto size-4" />
              </SidebarMenuButton>
            }
          ></DropdownMenuTrigger>
          <DropdownMenuContent
            className="w-(--radix-dropdown-menu-trigger-width) min-w-56 rounded-lg"
            side={isMobile ? "bottom" : "right"}
            align="end"
            sideOffset={4}
          >
            <DropdownMenuGroup>
              <DropdownMenuLabel className="p-0 font-normal">
                <div className="flex items-center gap-2 px-1 py-1.5 text-left text-sm">
                  <Avatar className="h-8 w-8 rounded-lg">
                    <AvatarImage src={avatarSrc} />
                    <AvatarFallback className="rounded-lg">
                      {avatarFallback}
                    </AvatarFallback>
                  </Avatar>
                  <div className="grid flex-1 text-left text-sm leading-tight">
                    <span className="truncate font-medium">
                      {account?.name}
                    </span>
                    <span className="truncate text-xs">
                      {account?.username}
                    </span>
                  </div>
                </div>
              </DropdownMenuLabel>
            </DropdownMenuGroup>
            <DropdownMenuSeparator />
            <DropdownMenuGroup>
              <DropdownMenuItem>
                <Sparkles />
                Upgrade to Pro
              </DropdownMenuItem>
            </DropdownMenuGroup>
            <DropdownMenuSeparator />
            <DropdownMenuGroup>
              <DropdownMenuItem>
                <BadgeCheck />
                Account
              </DropdownMenuItem>
              <DropdownMenuItem>
                <Bell />
                Notifications
              </DropdownMenuItem>
            </DropdownMenuGroup>
            <DropdownMenuSeparator />
            <DropdownMenuItem onClick={handleAccountSwitch}>
              <Users />
              Switch Account
            </DropdownMenuItem>
            <DropdownMenuItem onClick={handleLogout}>
              <LogOut />
              Log out
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
      </SidebarMenuItem>
    </SidebarMenu>
  );
}
