// svc/portal/src/components/chatbox/chatbox.tsx
"use client";

import { Button } from "@lerpz/ui/components/button";
import { Card, CardContent } from "@lerpz/ui/components/card";
import { Textarea } from "@lerpz/ui/components/textarea";
import { cn } from "@lerpz/ui/lib/utils";
import { ArrowUp, LoaderPinwheel } from "lucide-react";
import { motion } from "motion/react";
import type { ChangeEventHandler } from "react";
import { useEffect, useRef } from "react";
import ImageShelf from "./image-shelf";
import { type ChatboxMode, useChatbox } from "./provider";
import ChatboxSettings from "./settings";
import { useChatboxStore } from "./store";

interface PromptInputProps {
  isMobile: boolean;
  className?: string;
}

const settingsVariants = {
  visible: {
    opacity: 1,
    height: "auto",
    transition: { duration: 0.2, ease: "easeOut" },
  },
  hidden: {
    opacity: 0,
    height: 0,
    transition: { duration: 0.2, ease: "easeIn" },
  },
} as const;

const chatareaPlaceholder: Record<ChatboxMode, string> = {
  chat: "Send a message!",
  image: "Describe your image!",
  video: "Describe your video!",
};

export default function Chatbox() {
  const { isPending, showSettings } = useChatbox();

  useEffect(() => {
    if (!isPending) return;

    const handleBeforeUnload = (event: BeforeUnloadEvent) => {
      event.preventDefault();
      return "";
    };

    window.addEventListener("beforeunload", handleBeforeUnload);

    return () => {
      window.removeEventListener("beforeunload", handleBeforeUnload);
    };
  }, [isPending]);

  return (
    <motion.div
      initial={{ opacity: 0 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.25, ease: "easeIn" }}
    >
      <aside className="absolute bottom-0 left-1/2 transform -translate-x-1/2 w-full max-w-[750px] p-4">
        <ImageShelf />
        <Card className="rounded-4xl">
          <CardContent className="flex flex-col">
            <PromptInput isMobile={true} />
            <ChatboxToolbar />
            <motion.div
              variants={settingsVariants}
              animate={showSettings ? "visible" : "hidden"}
              transition={{ duration: 0.67, ease: "easeOut" }}
            >
              <ChatboxSettings />
            </motion.div>
          </CardContent>
        </Card>
      </aside>
    </motion.div>
  );
}

function ChatboxToolbar() {
  const { isPending, submit, isSubmitPending } = useChatbox();

  const { prompt } = useChatboxStore();

  return (
    <div className="flex gap-4">
      {/* TEXT AREA */}
      <PromptInput className="grow" isMobile={false} />

      {/* GENERATE BUTTON */}
      <Button
        size="icon"
        onClick={submit}
        disabled={isPending || !prompt?.trim()}
        aria-label="Send prompt"
      >
        {isSubmitPending ? (
          <LoaderPinwheel className="animate-spin" />
        ) : (
          <ArrowUp />
        )}
      </Button>
    </div>
  );
}

function PromptInput({ isMobile, className }: PromptInputProps) {
  const textareaRef = useRef<HTMLTextAreaElement>(null);

  const { mode: variant, isPending } = useChatbox();
  const { prompt, setPrompt } = useChatboxStore();

  const handleChange: ChangeEventHandler<HTMLTextAreaElement> = (e) => {
    setPrompt(e.target.value);
  };

  useEffect(() => {
    textareaRef.current?.focus();
  }, []);

  return (
    <Textarea
      ref={textareaRef}
      disabled={isPending}
      placeholder={chatareaPlaceholder[variant]}
      value={prompt}
      onChange={handleChange}
      className={cn(
        "grow border-none ring-none outline-none",
        className,
        isMobile ? "block sm:hidden" : "hidden sm:block",
      )}
    />
  );
}

// svc/coruscant/src/lib/components/chatbox/Chatbox.svelte
<script lang="ts">
import Icon from "@iconify/svelte";
import { Button } from "@lerpz/ui/components/button";
import { Card, CardContent } from "@lerpz/ui/components/card";
import { untrack } from "svelte";
import type { Model } from "$lib/ai/models.svelte.js";
import { chatboxStore } from "$lib/components/chatbox/chatbox.store.svelte.js";
import ChatboxSettings from "./ChatboxSettings.svelte";
import ChatStatusBar from "./ChatStatusBar.svelte";
import type {
    ChatboxMode,
    ChatboxSubmitArgs,
} from "./chatbox-context.svelte.js";
import { setChatboxContext } from "./chatbox-context.svelte.js";
import ImageShelf from "./ImageShelf.svelte";
import MarkdownEditor from "./MarkdownEditor.svelte";

const placeholders: Record<ChatboxMode, string> = {
    chat: "Send a message!",
    image: "Describe your image!",
    video: "Describe your video!",
};

let {
    onSubmit,
    onEnhance,
    models = [],
    isModelsLoading = false,
    isStreaming = false,
    isThinking = false,
    isSaved = false,
    error = null,
    loadModels = async () => {},
    defaultMode = "chat",
}: {
    onSubmit?: (args: ChatboxSubmitArgs) => void | Promise<void>;
    onEnhance?: (prompt: string) => Promise<string>;
    models?: Model[];
    isModelsLoading?: boolean;
    isStreaming?: boolean;
    isThinking?: boolean;
    isSaved?: boolean;
    error?: string | null;
    loadModels?: (mode?: string) => Promise<void>;
    defaultMode?: ChatboxMode;
} = $props();

let mode = $state<ChatboxMode>(untrack(() => defaultMode));
let showSettings = $state(true);
let isSubmitPending = $state(false);
let isEnhancePending = $state(false);

const isPending = $derived(isSubmitPending || isEnhancePending || isStreaming);

let cardEl = $state<HTMLDivElement | null>(null);

$effect(() => {
    chatboxStore.setChatboxAnchor(cardEl);
});

$effect(() => {
    if (isModelsLoading || models.length === 0) return;
    if (chatboxStore.model !== null) return;
    const first = models[0];
    if (first) chatboxStore.setModel(first.value);
});

$effect(() => {
    if (!isPending) return;
    const handler = (e: BeforeUnloadEvent) => {
        e.preventDefault();
        return "";
    };
    window.addEventListener("beforeunload", handler);
    return () => window.removeEventListener("beforeunload", handler);
});

setChatboxContext({
    get mode() {
        return mode;
    },
    setMode: (m) => {
        mode = m;
    },
    get showSettings() {
        return showSettings;
    },
    setShowSettings: (v) => {
        showSettings = v;
    },
    allowImageUploads: true,
    get models() {
        return models;
    },
    get isModelsLoading() {
        return isModelsLoading;
    },
    get loadModels() {
        return loadModels;
    },
    submit,
    get isSubmitPending() {
        return isSubmitPending;
    },
    enhance,
    get isEnhancePending() {
        return isEnhancePending;
    },
    get isPending() {
        return isPending;
    },
});

async function submit() {
    const trimmed = chatboxStore.prompt.trim();
    if (!trimmed || isPending) return;
    const args: ChatboxSubmitArgs = {
        prompt: trimmed,
        mode,
        model: chatboxStore.model,
        modelSettings: chatboxStore.getModelSettings(
            chatboxStore.model ?? undefined,
        ),
        images: chatboxStore.uploadedImages,
    };
    isSubmitPending = true;
    try {
        if (onSubmit) await onSubmit(args);
        chatboxStore.setPrompt("");
        chatboxStore.clearUploadedImages();
    } finally {
        isSubmitPending = false;
    }
}

async function enhance(prompt: string): Promise<string> {
    if (!onEnhance) return prompt;
    isEnhancePending = true;
    try {
        return await onEnhance(prompt);
    } finally {
        isEnhancePending = false;
    }
}

function handleEnter() {
    if (!isPending && chatboxStore.prompt.trim()) submit();
}
</script>

<aside class="absolute bottom-0 left-1/2 -translate-x-1/2 w-full max-w-[1024px] p-4">
  <ImageShelf />
  <ChatStatusBar {isThinking} {isSaved} {error} />
  <div bind:this={cardEl}>
    <Card class="rounded-4xl">
      <CardContent class="flex flex-col gap-2 p-4">
        <div class="flex items-end gap-4">
          <MarkdownEditor
            value={chatboxStore.prompt}
            onChange={(md) => chatboxStore.setPrompt(md)}
            onEnter={handleEnter}
            disabled={isPending}
            placeholder={placeholders[mode]}
            autofocus
            class="grow self-stretch px-1 py-1.5"
          />
          <Button
            variant="ghost"
            size="icon"
            onclick={submit}
            disabled={isPending || !chatboxStore.prompt.trim()}
            aria-label="Send prompt"
          >
            {#if isPending}
              <Icon icon="fa6-solid:spinner" class="animate-spin" />
            {:else}
              <Icon icon="fa6-solid:arrow-up" />
            {/if}
          </Button>
        </div>
        <!-- Settings row -->
        {#if showSettings}
          <ChatboxSettings {enhance} {isPending} {isEnhancePending} />
        {/if}
      </CardContent>
    </Card>
  </div>
</aside>
