// svc/coruscant/src/lib/components/chatbox/ModelSelector.svelte
<script lang="ts">
import Icon from "@iconify/svelte";
import { Badge } from "@lerpz/ui/components/badge";
import {
    Popover,
    PopoverContent,
    PopoverPositioner,
    PopoverTrigger,
} from "@lerpz/ui/components/popover";
import { ScrollArea } from "@lerpz/ui/components/scroll-area";
import { cn } from "@lerpz/ui/lib/utils";
import { type Model, modelFamilyLogo } from "$lib/ai/models.svelte.js";
import { chatboxStore } from "$lib/components/chatbox/chatbox.store.svelte.js";
import { getChatboxContext } from "./chatbox-context.svelte.js";

const chatbox = getChatboxContext();

const sortedModels = $derived<Model[]>(
    [...chatbox.models].sort(
        (a, b) =>
            a.family.localeCompare(b.family) || a.label.localeCompare(b.label),
    ),
);

let open = $state(false);
let previewValue = $state<string | null>(null);

const selectedModel = $derived<Model | null>(
    sortedModels.find((m) => m.value === chatboxStore.model) ?? null,
);

const previewModel = $derived<Model | null>(
    sortedModels.find((m) => m.value === previewValue) ??
        selectedModel ??
        sortedModels[0] ??
        null,
);

function handleOpenChange(details: { open: boolean }) {
    open = details.open;
    if (details.open) previewValue = chatboxStore.model;
}

function selectModel(value: string | null) {
    chatboxStore.setModel(value);
    open = false;
}

function handleListKeydown(e: KeyboardEvent) {
    const models = sortedModels;
    if (models.length === 0) return;
    const currentIndex = models.findIndex((m) => m.value === previewValue);
    if (e.key === "ArrowDown") {
        e.preventDefault();
        const next = models[(currentIndex + 1 + models.length) % models.length];
        if (next) previewValue = next.value;
    } else if (e.key === "ArrowUp") {
        e.preventDefault();
        const prev = models[(currentIndex - 1 + models.length) % models.length];
        if (prev) previewValue = prev.value;
    } else if (e.key === "Enter" && previewModel) {
        e.preventDefault();
        selectModel(previewModel.value);
    }
}
</script>

<Popover
  {open}
  onOpenChange={handleOpenChange}
  positioning={{
    placement: "top",
    gutter: 8,
    sameWidth: true,
    getAnchorRect: () =>
      chatboxStore.chatboxAnchor?.getBoundingClientRect() ?? null,
  }}
>
  <PopoverTrigger
    class={cn(
      "inline-flex h-9 items-center gap-1.5 rounded-4xl px-3 text-sm",
      "border border-transparent bg-transparent transition-colors",
      "hover:bg-muted dark:hover:bg-muted/50",
      "data-[state=open]:bg-muted dark:data-[state=open]:bg-muted/50",
    )}
    aria-label="Select model"
  >
    {#if chatbox.isModelsLoading}
      <Icon icon="fa6-solid:spinner" class="animate-spin" />
    {:else if selectedModel}
      <img
        src={modelFamilyLogo(selectedModel.family)}
        alt=""
        class="size-4 shrink-0 object-contain"
      />
    {:else}
      <Icon icon="fa6-solid:robot" />
    {/if}
    <span class="max-w-40 truncate">
      {selectedModel?.label ?? "Select model"}
    </span>
    <Icon icon="fa6-solid:angle-up" class="size-4 opacity-60" />
  </PopoverTrigger>

  <PopoverPositioner>
    <PopoverContent
      class="flex h-[360px] w-full max-w-[760px] overflow-hidden p-0"
    >
      <!-- Model list -->
      <div class="flex w-fit max-w-[250px] shrink-0 flex-col border-r">
        <div class="px-3 pt-3 pb-1.5 text-xs font-medium text-muted-foreground">
          Models
        </div>
        <ul aria-hidden="true" class="invisible h-0 shrink-0 p-1.5">
          {#each sortedModels as model (model.value)}
            <li class="flex items-center gap-2 px-2.5 py-2 text-sm">
              <span class="size-4 shrink-0"></span>
              <span class="whitespace-nowrap">{model.label}</span>
              {#if model.value === chatboxStore.model}
                <span class="size-4 shrink-0"></span>
              {/if}
            </li>
          {/each}
        </ul>
        <!-- svelte-ignore a11y_no_noninteractive_tabindex -->
        <ul
          class="flex min-h-0 flex-1 flex-col gap-0.5 overflow-y-auto p-1.5"
          tabindex="0"
          role="listbox"
          aria-label="Available models"
          onkeydown={handleListKeydown}
        >
          {#if chatbox.isModelsLoading}
            <li class="px-3 py-2 text-sm text-muted-foreground">
              <Icon icon="fa6-solid:spinner" class="mr-1.5 inline animate-spin" />
              Loading models…
            </li>
          {:else if chatbox.models.length === 0}
            <li class="px-3 py-2 text-sm text-muted-foreground">
              No models available
            </li>
          {:else}
            {#each sortedModels as model (model.value)}
              {@const isSelected = model.value === chatboxStore.model}
              {@const isPreview = model.value === previewModel?.value}
              <li role="option" aria-selected={isSelected}>
                <button
                  type="button"
                  class={cn(
                    "flex w-full items-center gap-2 rounded-md px-2.5 py-2 text-left text-sm transition-colors",
                    "hover:bg-muted dark:hover:bg-muted/50",
                    isPreview && "bg-muted dark:bg-muted/50",
                  )}
                  onmouseenter={() => (previewValue = model.value)}
                  onfocus={() => (previewValue = model.value)}
                  onclick={() => selectModel(model.value)}
                >
                  <img
                    src={modelFamilyLogo(model.family)}
                    alt=""
                    class="size-4 shrink-0 object-contain"
                  />
                  <span class="min-w-0 grow truncate">{model.label}</span>
                  {#if isSelected}
                    <Icon
                      icon="fa6-solid:check"
                      class="size-4 shrink-0 text-primary"
                    />
                  {/if}
                </button>
              </li>
            {/each}
          {/if}
        </ul>
      </div>

      <!-- Model details -->
      <div class="flex flex-1 flex-col">
        {#if previewModel}
          <ScrollArea orientation="vertical" class="flex-1">
            <div class="flex flex-col gap-4 p-4">
              <div class="flex items-start gap-3">
                <img
                  src={modelFamilyLogo(previewModel.family)}
                  alt=""
                  class="size-9 shrink-0 object-contain"
                />
                <div class="flex flex-col gap-1">
                  <h3 class="text-base leading-tight font-semibold">
                    {previewModel.label}
                  </h3>
                  {#if previewModel.provider || previewModel.family}
                    <p class="text-xs text-muted-foreground">
                      {[previewModel.provider, previewModel.family]
                        .filter(Boolean)
                        .join(" · ")}
                    </p>
                  {/if}
                </div>
              </div>

              {#if previewModel.description}
                <p class="text-sm leading-relaxed text-muted-foreground">
                  {previewModel.description}
                </p>
              {/if}

              {#if previewModel.modalities.length > 0 || previewModel.features.length > 0}
                <div class="flex flex-col gap-2">
                  <span class="text-xs font-medium text-muted-foreground">
                    Tags
                  </span>
                  <div class="flex flex-wrap gap-1.5">
                    {#each previewModel.modalities as modality (modality)}
                      <Badge variant="secondary">{modality}</Badge>
                    {/each}
                    {#each previewModel.features as feature (feature)}
                      <Badge variant="outline">{feature}</Badge>
                    {/each}
                  </div>
                </div>
              {/if}
            </div>
          </ScrollArea>

          <div class="border-t p-3">
            <button
              type="button"
              class={cn(
                "flex w-full items-center justify-center gap-1.5 rounded-md px-3 py-2 text-sm font-medium transition-colors",
                previewModel.value === chatboxStore.model
                  ? "bg-muted text-muted-foreground"
                  : "bg-primary text-primary-foreground hover:bg-primary/90",
              )}
              disabled={previewModel.value === chatboxStore.model}
              onclick={() => selectModel(previewModel.value)}
            >
              {#if previewModel.value === chatboxStore.model}
                <Icon icon="fa6-solid:check" class="size-4" />
                Selected
              {:else}
                Use this model
              {/if}
            </button>
          </div>
        {:else}
          <div
            class="flex flex-1 items-center justify-center p-4 text-sm text-muted-foreground"
          >
            Select a model to see details
          </div>
        {/if}
      </div>
    </PopoverContent>
  </PopoverPositioner>
</Popover>

// svc/portal/src/components/chatbox/model-selector.tsx
"use client";

import { Button } from "@lerpz/ui/components/button";
import {
  Popover,
  PopoverBackdrop,
  PopoverContent,
  PopoverClose,
  PopoverPortal,
  PopoverPositioner,
  PopoverTrigger,
} from "@lerpz/ui/components/popover";
import { ScrollArea } from "@lerpz/ui/components/scroll-area";
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@lerpz/ui/components/select";
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger,
} from "@lerpz/ui/components/tooltip";
import { cn } from "@lerpz/ui/lib/utils";
import { MdSmartToy, MdCheck, MdLoop, MdClose } from "react-icons/md";
import type { Model, ModelSetting } from "@/hooks/useModels";
import { useChatbox } from "./provider";
import { useChatboxStore } from "./store";

export function ModelSelectorTrigger() {
  const { models, isModelsLoading } = useChatbox();
  const { model: selectedModel, chatboxAnchor } = useChatboxStore();

  const selected = models.find((m) => m.value === selectedModel);

  return (
    <Popover>
      <PopoverTrigger
        render={
          <Button
            variant="outline"
            disabled={isModelsLoading}
            className="gap-1.5"
          >
            {isModelsLoading ? (
              <MdLoop className="animate-spin" />
            ) : (
              <MdSmartToy />
            )}
            <span className="text-sm truncate max-w-[120px]">
              {selected ? selected.label : "Select model"}
            </span>
          </Button>
        }
      />
      <PopoverBackdrop />
      <PopoverPortal>
        <PopoverPositioner side="top" sideOffset={12} align="center" anchor={chatboxAnchor}>
          <PopoverContent className="w-[600px] h-[500px] flex overflow-hidden p-0">
            <ModelSelectorPanel />
          </PopoverContent>
        </PopoverPositioner>
      </PopoverPortal>
    </Popover>
  );
}

function ModelSelectorPanel() {
  const { models, isModelsLoading } = useChatbox();
  const { model: selectedModel } = useChatboxStore();

  const selectedModelData = models.find((m) => m.value === selectedModel);

  return (
    <>
      {/* Left column — model list */}
      <div className="w-[220px] shrink-0 border-r flex flex-col overflow-hidden">
        <div className="px-4 py-3 border-b">
          <h3 className="text-sm font-medium">Models</h3>
        </div>

        {isModelsLoading ? (
          <div className="flex-1 flex items-center justify-center">
            <div className="flex flex-col items-center gap-2">
              <MdLoop className="size-5 animate-spin text-muted-foreground" />
              <p className="text-xs text-muted-foreground">Loading...</p>
            </div>
          </div>
        ) : models.length === 0 ? (
          <div className="flex-1 flex items-center justify-center">
            <p className="text-xs text-muted-foreground">
              No models available
            </p>
          </div>
        ) : (
          <ScrollArea className="flex-1 overflow-hidden">
            <div className="p-1.5 flex flex-col gap-0.5">
              {models.map((m) => (
                <ModelListItem
                  key={m.value ?? "default"}
                  model={m}
                  isSelected={selectedModel === m.value}
                />
              ))}
            </div>
          </ScrollArea>
        )}
      </div>

      {/* Right column — details + settings */}
      <div className="flex-1 flex flex-col overflow-hidden">
        <div className="flex items-center justify-end px-2 py-1.5 border-b">
          <PopoverClose
            render={
              <Button
                variant="ghost"
                size="icon-xs"
                aria-label="Close model selector"
              >
                <MdClose />
              </Button>
            }
          />
        </div>
        {selectedModelData ? (
          <ModelDetail model={selectedModelData} />
        ) : (
          <div className="flex-1 flex items-center justify-center px-6">
            <p className="text-sm text-muted-foreground text-center">
              Select a model to view its details and settings.
            </p>
          </div>
        )}
      </div>
    </>
  );
}

function ModelListItem({
  model,
  isSelected,
}: {
  model: Model;
  isSelected: boolean;
}) {
  const { setModel } = useChatboxStore();

  return (
    <button
      type="button"
      onClick={() => setModel(model.value)}
      className={cn(
        "w-full rounded-lg px-3 py-2 text-left transition-colors",
        "hover:bg-accent hover:text-accent-foreground",
        "focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring",
        isSelected && "bg-accent text-accent-foreground",
      )}
    >
      <div className="flex items-center gap-2">
        <MdSmartToy className="size-3.5 shrink-0 text-muted-foreground" />
        <span className="text-sm font-medium truncate">{model.label}</span>
        {isSelected && (
          <MdCheck className="size-3.5 shrink-0 text-primary ml-auto" />
        )}
      </div>
    </button>
  );
}

function ModelDetail({ model }: { model: Model }) {
  const { getModelSetting, setModelSetting } = useChatboxStore();

  return (
    <ScrollArea className="flex-1 overflow-hidden">
      <div className="p-4 flex flex-col gap-5">
        {/* Header */}
        <div>
          <h3 className="text-base font-semibold">{model.label}</h3>
          {model.description && (
            <p className="mt-1.5 text-sm text-muted-foreground leading-relaxed">
              {model.description}
            </p>
          )}
        </div>

        {/* Features / modalities */}
        <div className="flex flex-wrap gap-1.5">
          {model.modalities.map((mod) => (
            <span
              key={mod}
              className="rounded-full bg-primary/10 px-2.5 py-0.5 text-xs font-medium text-primary"
            >
              {mod}
            </span>
          ))}
          {model.features.map((feat) => (
            <span
              key={feat}
              className="rounded-full bg-muted px-2.5 py-0.5 text-xs font-medium text-muted-foreground"
            >
              {feat}
            </span>
          ))}
        </div>

        {/* Settings */}
        {model.settings.length > 0 && (
          <div className="flex flex-col gap-3">
            <h4 className="text-sm font-medium text-muted-foreground">
              Settings
            </h4>
            <div className="flex flex-col gap-3">
              {model.settings.map((setting) => (
                <ModelSettingRow
                  key={setting.key}
                  setting={setting}
                  currentValue={
                    getModelSetting(model.value ?? undefined, setting.key) ??
                    setting.defaultValue ??
                    null
                  }
                  onChange={(value) => {
                    if (model.value) {
                      setModelSetting(model.value, setting.key, value);
                    }
                  }}
                />
              ))}
            </div>
          </div>
        )}
      </div>
    </ScrollArea>
  );
}

function ModelSettingRow({
  setting,
  currentValue,
  onChange,
}: {
  setting: ModelSetting;
  currentValue: string | null;
  onChange: (value: string | null) => void;
}) {
  const Icon = setting.icon;

  const items = setting.values.map((v) => ({
    label: v.label,
    value: String(v.value),
  }));

  return (
    <div className="flex items-center justify-between gap-3">
      <Tooltip>
        <TooltipTrigger
          render={
            <div className="flex items-center gap-2 min-w-0">
              <Icon className="size-3.5 shrink-0 text-muted-foreground" />
              <span className="text-sm truncate">{setting.name}</span>
            </div>
          }
        />
        <TooltipContent>
          <p>{setting.tooltip}</p>
        </TooltipContent>
      </Tooltip>

      <Select items={items} value={currentValue} onValueChange={onChange}>
        <SelectTrigger size="sm" className="w-[120px] shrink-0">
          <SelectValue placeholder="Default" />
        </SelectTrigger>
        <SelectContent className="w-fit" alignItemWithTrigger={false}>
          <SelectGroup>
            {items.map((item) => (
              <SelectItem key={item.value} value={item.value}>
                {item.label}
              </SelectItem>
            ))}
          </SelectGroup>
        </SelectContent>
      </Select>
    </div>
  );
}
