// packages/ui/src/components/textarea.tsx
import { cn } from "@lerpz/ui/lib/utils";
import type * as React from "react";

function Textarea({ className, ...props }: React.ComponentProps<"textarea">) {
  return (
    <textarea
      data-slot="textarea"
      className={cn(
        "border-input bg-input/30 focus-visible:border-ring focus-visible:ring-ring/50 aria-invalid:ring-destructive/20 dark:aria-invalid:ring-destructive/40 aria-invalid:border-destructive dark:aria-invalid:border-destructive/50 resize-none rounded-xl border px-3 py-3 text-base transition-colors focus-visible:ring-[3px] aria-invalid:ring-[3px] md:text-sm placeholder:text-muted-foreground flex field-sizing-content min-h-16 w-full outline-none disabled:cursor-not-allowed disabled:opacity-50",
        className,
      )}
      {...props}
    />
  );
}

export { Textarea };

// packages/ui/src/components/textarea/Textarea.svelte
<script lang="ts">
import type { HTMLTextareaAttributes } from "svelte/elements";
import { cn } from "../../lib/utils.js";

let {
    class: className = "",
    rows = 3,
    el = $bindable<HTMLTextAreaElement | null>(null),
    ...rest
}: HTMLTextareaAttributes & { el?: HTMLTextAreaElement | null } = $props();
</script>
<textarea
  data-slot="textarea"
  {rows}
  bind:this={el}
  class={cn(
    "flex w-full px-3 py-2 text-sm",
    "bg-input/30 rounded-2xl border border-input transition-colors resize-none",
    "placeholder:text-muted-foreground",
    "focus-visible:border-ring focus-visible:ring-ring/50",
    "focus-visible:ring-[3px] focus-visible:outline-none",
    "disabled:cursor-not-allowed disabled:opacity-50",
    className
  )}
  {...rest}
></textarea>
