// svc/portal/src/components/theme-button.tsx
"use client";

import { Button } from "@lerpz/ui/components/button";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@lerpz/ui/components/tooltip";
import { Moon, Sun } from "lucide-react";
import { useTheme } from "next-themes";

export function ThemeButton() {
  const { setTheme, theme } = useTheme();

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger
          render={
            <Button
              variant="ghost"
              size="icon"
              onClick={() => setTheme(theme === "dark" ? "light" : "dark")}
            >
              <Sun className="h-5 w-5 rotate-0 scale-100 transition-all dark:-rotate-90 dark:scale-0" />
              <Moon className="absolute h-5 w-5 rotate-90 scale-0 transition-all dark:rotate-0 dark:scale-100" />
              <span className="sr-only">Toggle theme</span>
            </Button>
          }
        />
        <TooltipContent>
          <p>Toggle theme</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}

// svc/app/src/lib/components/ThemeButton.svelte
<script lang="ts">
import Icon from "@iconify/svelte";
import { Button } from "@lerpz/ui/components/button";
import {
    Tooltip,
    TooltipContent,
    TooltipTrigger,
} from "@lerpz/ui/components/tooltip";
import { mode, toggleMode } from "mode-watcher";
</script>

<Tooltip>
  <TooltipTrigger>
    {#snippet asChild(getProps)}
      <Button
        {...getProps()}
        variant="ghost"
        size="icon"
        onclick={toggleMode}
        aria-label="Toggle theme"
      >
        {#if $mode === "dark"}
          <Icon icon="fa6-solid:sun" class="h-5 w-5" />
        {:else}
          <Icon icon="fa6-solid:moon" class="h-5 w-5" />
        {/if}
        <span class="sr-only">Toggle theme</span>
      </Button>
    {/snippet}
  </TooltipTrigger>
  <TooltipContent>
    <p>Toggle theme</p>
  </TooltipContent>
</Tooltip>
