// packages/ui/src/components/separator.tsx
"use client";

import { Separator as SeparatorPrimitive } from "@base-ui/react/separator";

import { cn } from "@lerpz/ui/lib/utils";

function Separator({
  className,
  orientation = "horizontal",
  ...props
}: SeparatorPrimitive.Props) {
  return (
    <SeparatorPrimitive
      data-slot="separator"
      orientation={orientation}
      className={cn(
        "bg-border shrink-0 data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:w-px data-[orientation=vertical]:self-stretch",
        className,
      )}
      {...props}
    />
  );
}

export { Separator };

// packages/ui/src/components/separator/Separator.svelte
<script lang="ts">
import { cn } from "../../lib/utils.js";

let {
    class: className = "",
    orientation = "horizontal",
    ...rest
}: {
    class?: string;
    orientation?: "horizontal" | "vertical";
    [key: string]: unknown;
} = $props();
</script>
<div
  data-slot="separator"
  data-orientation={orientation}
  class={cn(
    "bg-border shrink-0",
    orientation === "horizontal" ? "h-px w-full" : "h-full w-px",
    className
  )}
  {...rest}
></div>
